src/KnowbaseBundle/Entity/Accounts.php
<?php

namespace KnowbaseBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Accounts
 *
 * @ORM\Table(name="accounts")
 * @ORM\Entity(repositoryClass="KnowbaseBundle\Repository\AccountsRepository")
 */
class Accounts extends BaseUser
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="Questions", mappedBy="accounts")
     */
    protected $questions;

    /**
     * @ORM\Column(name = "firstname", type="string")
     * @Assert\NotBlank(groups={"Registration", "Profile"})
     */
    protected $firstname;

    /**
     * @ORM\Column(name = "secondname", type="string")
     * @Assert\NotBlank(groups={"Registration", "Profile"})
     */
    protected $secondname;

    /**
     * @ORM\ManyToOne(targetEntity="Region", inversedBy="accounts")
     * @ORM\JoinColumn(name="region_id", referencedColumnName="id")
     * @Assert\NotBlank(groups={"Registration", "Profile"})
     */
    protected $region;

    /**
     * @var boolean
     */
    protected $sortStatus;

    /**
     * @var boolean
     */
    protected $sortTimeLogin;

    /**
     * @var boolean
     */
    protected $sortLongTimeWithoutLogin;

    public function __construct()
    {
        parent::__construct();
        $this->questions = new ArrayCollection();
    }

    /**
     * Add question
     *
     * @param \KnowbaseBundle\Entity\Questions $question
     *
     * @return Accounts
     */
    public function addQuestion(\KnowbaseBundle\Entity\Questions $question)
    {
        $this->questions[] = $question;

        return $this;
    }

    /**
     * Remove question
     *
     * @param \KnowbaseBundle\Entity\Questions $question
     */
    public function removeQuestion(\KnowbaseBundle\Entity\Questions $question)
    {
        $this->questions->removeElement($question);
    }

    /**
     * Get questions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getQuestions()
    {
        return $this->questions;
    }

    /**
     * Get Account id
     * @return \KnowbaseBundle\Entity\Accounts
     */
    public function getAccount()
    {
        return $this->getId();
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return Accounts
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set secondname
     *
     * @param string $secondname
     *
     * @return Accounts
     */
    public function setSecondname($secondname)
    {
        $this->secondname = $secondname;

        return $this;
    }

    /**
     * Get secondname
     *
     * @return string
     */
    public function getSecondname()
    {
        return $this->secondname;
    }

    /**
     * Set region
     *
     * @param \KnowbaseBundle\Entity\Region $region
     *
     * @return Accounts
     */
    public function setRegion(\KnowbaseBundle\Entity\Region $region = null)
    {
        $this->region = $region;

        return $this;
    }

    /**
     * Get region
     *
     * @return \KnowbaseBundle\Entity\Region
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function getSortStatus()
    {
        return $this->sortStatus;
    }

    public function setSortStatus($sort)
    {
        $this->sortStatus = $sort;

        return $this;
    }

    public function getSortTimeLogin()
    {
        return $this->sortTimeLogin;
    }

    public function setSortTimeLogin($sort)
    {
        $this->sortTimeLogin = $sort;

        return $this;
    }

    public function getSortLongTimeWithoutLogin()
    {
        return $this->sortLongTimeWithoutLogin;
    }

    public function setSortLongTimeWithoutLogin($sort)
    {
        $this->sortLongTimeWithoutLogin = $sort;

        return $this;
    }
}

src/KnowbaseBundle/Controller/DefaultController.php
<?php

namespace KnowbaseBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw $this->createAccessDeniedException();
        }
        return $this->render('KnowbaseBundle:Default:index.html.twig.twig');
    }

    public function secondAction()
    {
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw $this->createAccessDeniedException();
        }
        return $this->render('KnowbaseBundle:Default:second.html.twig');
    }
}

src/KnowbaseBundle/Resources/views/Default/list.html.twig
{% extends 'KnowbaseBundle::base.html.twig' %}

{% block body %}
    <style>
        pre {
            font-size: inherit;
            color: inherit;
            border: initial;
            padding: initial;
            font-family: inherit;
        }
    </style>
        {{ form_start(form) }}
        {{ form_errors(form) }}
    {#{% if not is_granted('ROLE_ADMIN') %}#}
    <div class="row">
        <div class="col-xs-2">
            <strong>Поиск вопросов по статусу:</strong> {{ form_widget(form.status, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>
    {#{% endif %}#}
    <div class="row">
    <div class="col-xs-5">
    {{ form_widget(form.question, {'attr': {'class': 'form-control', 'placeholder': 'Поиск вопроса по ключевым словам'}}) }}
    </div>
    </div>
    {{ form_row(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
    {{ form_end(form) }}
    <table class="table">
    <tr>
            <td align="center"><div class="colcell"> <strong> Вопрос: </strong></div></td>
            <td align="center"> <strong> Тема: </strong> </td>
            {% if is_granted('ROLE_ADMIN') %}
                <td align="center"> <strong> Автор: </strong> </td>
                <td align="center"> <strong> Регион: </strong> </td>
            {% endif %}
            <td align="center"> <strong> Дата: </strong> </td>
            <td align="center"> <strong> Статус: </strong> </td>
            <td align="center"> <strong> Приложение: </strong> </td>
            <td align="center"> <strong> Действие: </strong> </td>
        </tr>
    {% for question in questions %}
        <tr>
            <td><div class="colcell"> <pre>{{ question.Question }}</pre> </div></td>
            <td> {{ question.category.name }} </td>
            {% if is_granted('ROLE_ADMIN') %}
                <td> {{ question.account.firstname }} {{ question.account.secondname }} </td>
                <td> {{ question.account.region.name }} </td>
            {% endif %}
            <td> {{ question.timeTask|date('Y-m-d H:i:s') }} </td>
            <td>
                <a href="/Answer/{{ question.id }}/0">
                    {% if  question.status  == waiting %}
                        Ожидает ответа
                    {% endif %}
                    {% if  question.status  == publish %}
                        Опубликован
                    {% endif %}
                    {% if  question.status  == answered %}
                        Получен ответ
                    {% endif %}
                    {% if  question.status  == closed %}
                        Закрыт
                     {% endif %}
                </a>
            </td>
            <td>
            {% if question.ImageName != 'null' and question.ImageName != '' %}
                <a href="{{ vich_uploader_asset(question, 'imageFile') }}"> Приложение </a>
             {% endif %}
            </td>
             <td>
                {% if question.account.id == account_id %}
                {% if question.status != closed and question.status != publish %}
                <a href="/EditQuestion/{{ question.id }}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                {% endif %}
                {% if question.status != publish %}
                <a href="/RemoveQuestion/{{ question.id }}">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
                {% else %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="/RemoveQuestion/{{ question.id }}">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    {% endif %}
                {% endif %}
                {% endif %}
            </td>
        </tr>
     {% endfor %}
    </table>
{% endblock %}

src/KnowbaseBundle/Resources/views/Default/listPublic.html.twig
{% extends 'KnowbaseBundle::base.html.twig' %}

{% block body %}
    <style>
        pre {
            font-size: medium;
            color: inherit;
            border: initial;
            padding: initial;
            font-family: inherit;
            background-color: inherit;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="navbar-collapse collapse sidebar-navbar-collapse" style="background-color: #D4DBE3"><h3>Темы:</h3></div>
                <div class="sidebar-nav">
                    <div class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <span class="visible-xs navbar-brand">Sidebar menu</span>
                        </div>
                        <div class="navbar-collapse collapse sidebar-navbar-collapse" style="background-color: #d0e9c6">
                            <ul class="nav navbar-nav">
                            {% for category in categories %}
                                <li><a href="#cat-{{ category.id }}"><strong>{{ category.name }}</strong></a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-9">
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for category in categories %}
                        <div id="cat-{{ category.id }}"><div class="navbar-collapse collapse sidebar-navbar-collapse" style="background-color: #D4DBE3"><h3>{{ category.name }}</h3></div></div>
                            {% for question in category.questions %}
                                {% if question.status == publish %}
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab">
                                            <h4 class="panel-title">
                                                <a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" data-target="#q-{{ question.id }}"
                                                   aria-expanded="false" aria-controls="{{ question.id }}">{{ question.Question }}</a>
                                            </h4>
                                         </div>
                            {% for answer in question.answers %}
                                <div id="q-{{ question.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ answer.id }}">
                                    <div class="panel-body">
                                         <pre>{{ answer.answer }}</pre>
                                        {% if is_granted('ROLE_ADMIN') %}
                                            <a href="/EditAnswer/{{ answer.id }}">
                                                <span class="btn btn-primary">Редактировать ответ</span>
                                            </a>
                                            <span>Автор последней публикации ответа: {{ answer.username }}</span>
                                        {% endif %}
                                        <p>
                                    {% if answer.ImageName != 'null' and  answer.ImageName != '' %}
                                         <a href="{{ vich_uploader_asset(answer, 'imageFile') }}"> Приложение </a>
                                    {% endif %}
                                        </p>
                                    </div>
                                </div>
                            {% endfor %}
                                     </div>
                                {% endif %}
                            {% endfor %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/KnowbaseBundle/Resources/views/Default/settasksuccess.html.twig
{% extends 'KnowbaseBundle::base.html.twig' %}

{% block body %}
<h3>Спасибо за ваше обращение! Ожидайте ответа.</h3>
{% endblock %}

src/KnowbaseBundle/Resources/views/Default/test.html.twig
{% extends 'KnowbaseBundle::base.html.twig' %}

{% block body %}
{{ account }}
{% endblock %}